// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idyjpwmjasrclsamceqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkeWpwd21qYXNyY2xzYW1jZXFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NTExNTAsImV4cCI6MjA3MzEyNzE1MH0.hezdTPwe90caeojJ-ZaoN-T4zXzc7aYA-40efDlVfsg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});